#!/bin/bash

cd $1
lastFrame=$(ls -1 frames/ | tail -n 1)
nframes=$(echo ${lastFrame%.*} | sed 's/^0*//')
echo "$nframes frames."

vidfilename=$(pwd | xargs basename).mp4
time ~/local/prefix/bin/ffmpeg -r 30 -i frames/%05d.sgi -c:v libx264 -r 24 \
    -pix_fmt yuv420p  -movflags faststart $vidfilename
